version: "3"

services:
  shoesandblouse.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    image: shoesandblouse.api
    build:
      context: .
      dockerfile: ShoesAndBlouse.API/Dockerfile
    depends_on: 
      - shoesandblouse.database
    ports:
      - "5000:5000"
      - "5001:5001"
    #networks: 
    #  - postgres-network
    volumes:
      - ./shoesandblouse-api-data/:/var/lib/api/
        
  shoesandblouse.database:
    image: postgres:latest
    container_name: shoesandblouse.database
    environment:
      - POSTGRES_DB=ShoesAndBlouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - HOS
    ports:
      - "5432:5432"
    #networks:
     # - postgres-network
    restart: always
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

#networks:
  #postgres-network:
    #driver: bridge